"""Render the Orbit IDE icon in every form the app needs.

    python3 scripts/build_icon.py

The geometry lives in ``scripts/orbitmark.swift`` (the Orbit family's comet
orbit with a pair of code chevrons in the centre). This compiles it with the
Xcode toolchain's ``swiftc`` (no Xcode licence needed), renders each size, and
writes:

* src-tauri/icons/*.png, icon.icns, icon.ico, icon.png (the macOS set
  ``cargo tauri build`` bundles: a white mark on the black macOS icon tile)
* src-tauri/icons/orbit-ide.svg (the macOS tile at 1024)
* ui/mark.svg (the in-app mark, a 32-unit black tile) and ui/logo.svg (the
  bare mark in currentColor)

Edit the geometry and re-run; never hand-edit the outputs.
"""

from __future__ import annotations

import pathlib
import shutil
import struct
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "scripts" / "orbitmark.swift"
ICONS = ROOT / "src-tauri" / "icons"
UI = ROOT / "ui"

TOOLCHAIN = pathlib.Path("/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin")
SDK = pathlib.Path("/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk")

INK = "#111111"
MAC_SCALE = 0.60
TILE_SCALE = 0.76


def compile_renderer(workdir: pathlib.Path) -> pathlib.Path:
    swiftc = TOOLCHAIN / "swiftc"
    if not swiftc.exists():
        swiftc = pathlib.Path(shutil.which("swiftc") or "swiftc")
    binary = workdir / "orbitmark"
    command = [str(swiftc), "-O", "-o", str(binary), str(SOURCE)]
    if SDK.exists():
        command[1:1] = ["-sdk", str(SDK)]
    subprocess.run(command, check=True)
    return binary


def render(binary: pathlib.Path, out: pathlib.Path, size: int, fg: str, bg: str, scale: float, *flags: str) -> bytes:
    subprocess.run([str(binary), str(out), str(size), str(size), fg, bg, str(scale), *flags], check=True)
    return out.read_bytes()


def svg_paths(binary: pathlib.Path, scale: float, ink: str, *flags: str) -> str:
    raw = subprocess.run([str(binary), "--svg", str(scale), *flags], check=True, capture_output=True, text=True).stdout
    return raw.replace("__INK__", ink)


def write(path: pathlib.Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    print(f"  {path.relative_to(ROOT)}  {len(data):,} bytes")


def write_icns(path: pathlib.Path, images: dict[str, bytes]) -> None:
    body = b"".join(code.encode("ascii") + struct.pack(">I", 8 + len(blob)) + blob for code, blob in images.items())
    write(path, b"icns" + struct.pack(">I", 8 + len(body)) + body)


def write_ico(path: pathlib.Path, images: list[tuple[int, bytes]]) -> None:
    header = struct.pack("<HHH", 0, 1, len(images))
    offset = 6 + 16 * len(images)
    entries, blobs = b"", b""
    for size, blob in images:
        dim = size if size < 256 else 0
        entries += struct.pack("<BBBBHHII", dim, dim, 0, 0, 1, 32, len(blob), offset)
        offset += len(blob)
        blobs += blob
    write(path, header + entries + blobs)


def indent(fragment: str, spaces: int) -> str:
    pad = " " * spaces
    return "".join(pad + line + "\n" for line in fragment.strip().splitlines())


def svg_mac(paths: str) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024" role="img" aria-label="Orbit IDE">\n'
        "  <!-- Orbit IDE: code in orbit. Generated by scripts/build_icon.py; edit scripts/orbitmark.swift, not this. -->\n"
        f'  <rect x="100" y="100" width="824" height="824" rx="185" fill="{INK}"/>\n'
        '  <g fill="#fff">\n' + indent(paths, 4) + "  </g>\n</svg>\n"
    )


def svg_logo(paths: str) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="112 112 800 800" width="64" height="64" role="img" aria-label="Orbit IDE">\n'
        "  <!-- Orbit IDE mark, bare, in currentColor. Generated by scripts/build_icon.py; edit scripts/orbitmark.swift, not this. -->\n"
        '  <g fill="currentColor">\n' + indent(paths, 4) + "  </g>\n</svg>\n"
    )


def svg_mark(paths: str) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="64" height="64" role="img" aria-label="Orbit IDE">\n'
        "  <!-- Orbit IDE mark. Generated by scripts/build_icon.py; edit scripts/orbitmark.swift, not this. -->\n"
        f'  <rect width="32" height="32" rx="7.2" fill="{INK}"/>\n'
        '  <g fill="#fff" transform="scale(0.03125)">\n' + indent(paths, 4) + "  </g>\n</svg>\n"
    )


def main() -> int:
    print("Orbit IDE icons")
    with tempfile.TemporaryDirectory() as tmp:
        work = pathlib.Path(tmp)
        binary = compile_renderer(work)
        png = work / "out.png"
        mac: dict[int, bytes] = {}
        for size in (16, 32, 48, 64, 128, 256, 512, 1024):
            flags = ("bold",) if size <= 48 else ()
            mac[size] = render(binary, png, size, "white", "mac-black", MAC_SCALE, *flags)
        for size, name in ((32, "32x32.png"), (64, "64x64.png"), (128, "128x128.png"), (256, "128x128@2x.png")):
            write(ICONS / name, mac[size])
        write(ICONS / "icon.png", mac[1024])
        write_icns(ICONS / "icon.icns", {
            "ic11": mac[32], "ic12": mac[64], "ic07": mac[128], "ic13": mac[256], "ic09": mac[512], "ic10": mac[1024],
        })
        write_ico(ICONS / "icon.ico", [(s, mac[s]) for s in (16, 32, 48, 64, 128, 256)])
        write(ICONS / "orbit-ide.svg", svg_mac(svg_paths(binary, MAC_SCALE, "#fff")).encode("utf-8"))
        write(UI / "mark.svg", svg_mark(svg_paths(binary, TILE_SCALE, "#fff", "bold")).encode("utf-8"))
        write(UI / "logo.svg", svg_logo(svg_paths(binary, 0.78, "currentColor")).encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
